services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: isuconp
    ports:
      - ${DB_PORT:-33306}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h127.0.0.1 -uroot -ppassword

volumes:
  mysql-data:
